# Generated by Django 5.0.4 on 2024-04-11 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('home', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('sort', models.CharField(max_length=50)),
                ('get_cities', models.BooleanField(default=True)),
                ('get_countries', models.BooleanField(default=True)),
                ('image_exists', models.BooleanField(default=True)),
                ('clicks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AwardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('award_show', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='award.awardcategory')),
            ],
        ),
    ]
