# Generated by Django 5.0.4 on 2024-04-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('medium_type', models.CharField(choices=[('Digital', 'Digital'), ('Other', 'Other')], max_length=20)),
                ('office', models.CharField(max_length=100)),
                ('entrant_company', models.CharField(max_length=100)),
                ('brand_client', models.CharField(max_length=100)),
                ('commissioning_client', models.CharField(max_length=100)),
                ('product_categories', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='award_entries/')),
                ('commissioning_client_contact', models.CharField(max_length=100)),
                ('commissioning_client_email', models.EmailField(max_length=254)),
                ('year_of_participation', models.PositiveIntegerField()),
                ('award_show', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('country_for_jury', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('placements', models.CharField(max_length=100)),
                ('case_study_description', models.TextField()),
                ('entry_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('entry_region', models.CharField(max_length=100)),
                ('immortal_score', models.FloatField()),
                ('total_score', models.FloatField()),
                ('moderation_status', models.CharField(max_length=20)),
                ('lbb_admin_email', models.EmailField(max_length=254)),
                ('categories', models.ManyToManyField(to='award.awardcategory')),
            ],
        ),
    ]
