# Generated by Django 5.0.4 on 2024-04-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0004_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=100)),
                ('winner', models.CharField(max_length=100)),
                ('result_name', models.CharField(max_length=100)),
                ('min_score', models.IntegerField(default=1)),
                ('max_score', models.IntegerField(default=500)),
                ('award_show', models.CharField(choices=[('New Creators Showcase', 'The New Creators Showcase'), ('Immortal Awards', 'The Immortal Awards')], max_length=100)),
            ],
        ),
    ]
