# Generated by Django 5.0.4 on 2024-04-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0006_remove_awardresult_result_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardShows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('submissions_start_date', models.DateTimeField()),
                ('submissions_deadline', models.DateTimeField()),
                ('online_judging_start_date', models.DateTimeField()),
                ('global_shortlist_date', models.DateTimeField()),
                ('final_judging_start_date', models.DateTimeField()),
                ('winners_announced_date', models.DateTimeField()),
                ('launch_date_from', models.DateTimeField()),
                ('launch_date_to', models.DateTimeField()),
                ('announce_results_till', models.DateTimeField()),
                ('office', models.CharField(max_length=200)),
                ('stop_submissions', models.BooleanField(default=False)),
                ('show_league_table', models.BooleanField(default=False)),
            ],
        ),
    ]
