# Generated by Django 5.0.4 on 2024-04-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0007_awardshows'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('logo', models.ImageField(upload_to='logo/')),
                ('isGlobal', models.BooleanField(default=False)),
                ('immortal', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Horror', 'Horror'), ('Animation', 'Animation'), ('Choreography', 'Choreography')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
