# Generated by Django 5.0.4 on 2024-04-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0008_awardsponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('from_entry_id', models.CharField(max_length=50)),
                ('to_entry_id', models.CharField(max_length=50)),
                ('show_in_frontend', models.BooleanField(default=False)),
                ('exists_in', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='awardsponsor',
            name='type',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Global', 'Global'), ('White Paper', 'White Paper'), ('North America', 'North America'), ('Europe', 'Europe'), ('Latin America', 'Latin America'), ('Middle East & Africa', 'Middle East & Africa'), ('Asia Pacific', 'Asia Pacific')], max_length=30),
        ),
    ]
