# Generated by Django 5.0.4 on 2024-04-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0009_awardmedia_alter_awardsponsor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardmedia',
            name='exists_in',
            field=models.CharField(choices=[('Campaign & Single', 'Campaign & Single'), ('Single', 'Single'), ('Campaign', 'Campaign')], max_length=100),
        ),
        migrations.CreateModel(
            name='CategoryMediumRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('from_entry_id', models.IntegerField()),
                ('to_entry_id', models.IntegerField()),
                ('region', models.ManyToManyField(to='award.region')),
            ],
        ),
    ]
