# Generated by Django 5.0.4 on 2024-04-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0010_alter_awardmedia_exists_in_categorymediumregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryForJuryAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('online_judging', models.BooleanField(default=False)),
                ('live_judging', models.BooleanField(default=False)),
            ],
        ),
    ]
