# Generated by Django 5.0.4 on 2024-04-15 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0011_countryforjuryallotment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Side',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('logo', models.ImageField(upload_to='logo/')),
                ('ribbon_title', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
                ('award_show', models.CharField(blank=True, choices=[('The Immortal Awards', 'The Immortal Awards'), ('The New Creators Showcase', 'The New Creators Showcase')], max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaggedCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('score', models.ImageField(default=1, upload_to='')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='award.awardentry')),
            ],
        ),
    ]
