# Generated by Django 5.0.4 on 2024-04-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0012_side_taggedcompanies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AwardJury',
        ),
        migrations.DeleteModel(
            name='AwardMedia',
        ),
        migrations.DeleteModel(
            name='AwardResult',
        ),
        migrations.DeleteModel(
            name='AwardShows',
        ),
        migrations.DeleteModel(
            name='AwardSponsor',
        ),
        migrations.RemoveField(
            model_name='categorymediumregion',
            name='region',
        ),
        migrations.DeleteModel(
            name='CountryForJuryAllotment',
        ),
        migrations.DeleteModel(
            name='Side',
        ),
        migrations.RemoveField(
            model_name='taggedcompanies',
            name='entry',
        ),
        migrations.DeleteModel(
            name='CategoryMediumRegion',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='TaggedCompanies',
        ),
    ]
