# Generated by Django 5.0.4 on 2024-04-17 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0013_delete_awardjury_delete_awardmedia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('award_show', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='jury_images/')),
                ('user_id', models.IntegerField()),
                ('is_super', models.BooleanField(default=False)),
                ('hide_from_final_judging', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AwardMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('from_entry_id', models.CharField(max_length=50)),
                ('to_entry_id', models.CharField(max_length=50)),
                ('show_in_frontend', models.BooleanField(default=False)),
                ('exists_in', models.CharField(choices=[('Campaign & Single', 'Campaign & Single'), ('Single', 'Single'), ('Campaign', 'Campaign')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AwardResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=100)),
                ('min_score', models.IntegerField(default=1)),
                ('max_score', models.IntegerField(default=500)),
                ('award_show', models.CharField(choices=[('New Creators Showcase', 'The New Creators Showcase'), ('Immortal Awards', 'The Immortal Awards')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AwardShows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('submissions_start_date', models.DateTimeField()),
                ('submissions_deadline', models.DateTimeField()),
                ('online_judging_start_date', models.DateTimeField()),
                ('global_shortlist_date', models.DateTimeField()),
                ('final_judging_start_date', models.DateTimeField()),
                ('winners_announced_date', models.DateTimeField()),
                ('launch_date_from', models.DateTimeField()),
                ('launch_date_to', models.DateTimeField()),
                ('announce_results_till', models.DateTimeField()),
                ('office', models.CharField(max_length=200)),
                ('stop_submissions', models.BooleanField(default=False)),
                ('show_league_table', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AwardSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('logo', models.ImageField(upload_to='logo/')),
                ('isGlobal', models.BooleanField(default=False)),
                ('immortal', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Global', 'Global'), ('White Paper', 'White Paper'), ('North America', 'North America'), ('Europe', 'Europe'), ('Latin America', 'Latin America'), ('Middle East & Africa', 'Middle East & Africa'), ('Asia Pacific', 'Asia Pacific')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryForJuryAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('online_judging', models.BooleanField(default=False)),
                ('live_judging', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Side',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('logo', models.ImageField(upload_to='logo/')),
                ('ribbon_title', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
                ('award_show', models.CharField(blank=True, choices=[('The Immortal Awards', 'The Immortal Awards'), ('The New Creators Showcase', 'The New Creators Showcase')], max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryMediumRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('from_entry_id', models.IntegerField()),
                ('to_entry_id', models.IntegerField()),
                ('region', models.ManyToManyField(to='award.region')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('score', models.ImageField(default=1, upload_to='')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='award.awardentry')),
            ],
        ),
    ]
