# Generated by Django 5.0.4 on 2024-04-16 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_jobs_jobapplicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='careers.craftcategory'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='office_type',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid(On-site & Remote)', 'Hybrid(On-site & Remote)')], max_length=100),
        ),
    ]
