# Generated by Django 5.0.4 on 2024-04-16 10:45

import location_field.models.plain
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_alter_jobs_category_alter_jobs_office_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='craftcategory',
            options={'verbose_name_plural': 'Craft Categories'},
        ),
        migrations.AlterModelOptions(
            name='jobapplicant',
            options={'verbose_name_plural': 'Job Applicants'},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name_plural': 'Jobs'},
        ),
        migrations.AddField(
            model_name='jobs',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=12345, max_length=63),
            preserve_default=False,
        ),
    ]
