# Generated by Django 5.0.4 on 2024-04-16 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_alter_craftcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='craftcategory',
            options={'verbose_name_plural': 'Jobs Categories'},
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('skill_set', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=100)),
                ('last_job', models.CharField(max_length=100)),
                ('past_jobs', models.TextField()),
                ('education', models.CharField(max_length=100)),
                ('links', models.URLField()),
                ('summary', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='careers.craftcategory')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='careers.skill')),
            ],
            options={
                'verbose_name_plural': 'Resumes',
            },
        ),
    ]
