# Generated by Django 5.0.4 on 2024-04-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_place',
            field=models.CharField(null=True),
        ),
    ]
